# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: ['1.21']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: "[Linux] Install PCAP libraries"
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -q
        sudo apt-get install libpcap-dev gcc

    - name: Build
      run: |
        mkdir bin/${{ matrix.version }}
        go build -v -o bin/${{ matrix.version}}/sipdump-${{ matrix.os }} 
        
